//USER TYPES
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOAD_USER_ARTICLES = "LOAD_USER_ARTICLES";
//ERROR TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//ARTICLE TYPES
export const LOAD_ARTICLE = "LOAD_ARTICLE";
